{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producerPlugin",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 1929,
          "sha512": "fbb04c6f87935ce663b06fc3189d7ddaeed1c5e1ba19f22cee830cdd329790adade4f43e768008e1a74bdfea01bec3a8f55684f0cd65e1546e91fbe2c8803379",
          "sha256": "a69b7234bf3fab16690607b55c86c46ce75da2da5626832d44aa088ea5c7ee30",
          "sha1": "f207910f982ac77b9e2f330cebc0044a201b8b98",
          "md5": "c1fc453284ab54dcbbe332760df7b6a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.23"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 1929,
          "sha512": "fbb04c6f87935ce663b06fc3189d7ddaeed1c5e1ba19f22cee830cdd329790adade4f43e768008e1a74bdfea01bec3a8f55684f0cd65e1546e91fbe2c8803379",
          "sha256": "a69b7234bf3fab16690607b55c86c46ce75da2da5626832d44aa088ea5c7ee30",
          "sha1": "f207910f982ac77b9e2f330cebc0044a201b8b98",
          "md5": "c1fc453284ab54dcbbe332760df7b6a9"
        }
      ]
    }
  ]
}
