{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producerPlugin",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 2016,
          "sha512": "e2020620cb96ea151b2c37ae8912be5fa18f12448d08d8849e6baa86357e95a5ff7cdf4e9fd2593720c6b6c16530be7af690ad2dcf9cc815424f6ddd76ff5e5d",
          "sha256": "936c874ef1e2dab04c43c40d9ddf1c997638b1e50b4acaf7019dcee2fe6aa347",
          "sha1": "1cd961dfbb07ceb3b53a1713b7eb0da086fbd54c",
          "md5": "398050f7c576e683d08dbb2b77fc064e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 2016,
          "sha512": "e2020620cb96ea151b2c37ae8912be5fa18f12448d08d8849e6baa86357e95a5ff7cdf4e9fd2593720c6b6c16530be7af690ad2dcf9cc815424f6ddd76ff5e5d",
          "sha256": "936c874ef1e2dab04c43c40d9ddf1c997638b1e50b4acaf7019dcee2fe6aa347",
          "sha1": "1cd961dfbb07ceb3b53a1713b7eb0da086fbd54c",
          "md5": "398050f7c576e683d08dbb2b77fc064e"
        }
      ]
    }
  ]
}
