{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producerPlugin",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 1914,
          "sha512": "09496a5d8c3d1685096cee34b7c30ebb0cbc078398f45d75bc2481204e42f55d6d19a9bbebdf4bac9cc20abe5930391ec241de9c249f0b73836440884fdac68b",
          "sha256": "a58cdc87157a7780546636524e34e5b97efaa2cb83206b5ff20b911f64efbd6a",
          "sha1": "caf39b85d1648dda605a53e5c0254a3f4c564cfa",
          "md5": "ef402806cea4d70a3fadd677567c4306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "producerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 1914,
          "sha512": "09496a5d8c3d1685096cee34b7c30ebb0cbc078398f45d75bc2481204e42f55d6d19a9bbebdf4bac9cc20abe5930391ec241de9c249f0b73836440884fdac68b",
          "sha256": "a58cdc87157a7780546636524e34e5b97efaa2cb83206b5ff20b911f64efbd6a",
          "sha1": "caf39b85d1648dda605a53e5c0254a3f4c564cfa",
          "md5": "ef402806cea4d70a3fadd677567c4306"
        }
      ]
    }
  ]
}
