{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "publishing-plugin-one",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "publishing-plugin-one-1.0.0-local-dev.jar",
          "url": "publishing-plugin-one-1.0.0-local-dev.jar",
          "size": 1819,
          "sha512": "2b9120957d58e183d1da1f8298b13b8bcebdd58b6047994e86fed7fa5345cb3e42d62590ec2ee3a586eb372a958890cd6e4c91807800b326467e2b05ff86b108",
          "sha256": "e4a946af03909a6af8e529d8ac1c33edc7f65b771708cd12bc36204916d60736",
          "sha1": "dff772064fa8c8fc89dadf1249396e9858178e66",
          "md5": "abab507cc184e500695cf3b8082d8098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "publishing-plugin-one-1.0.0-local-dev.jar",
          "url": "publishing-plugin-one-1.0.0-local-dev.jar",
          "size": 1819,
          "sha512": "2b9120957d58e183d1da1f8298b13b8bcebdd58b6047994e86fed7fa5345cb3e42d62590ec2ee3a586eb372a958890cd6e4c91807800b326467e2b05ff86b108",
          "sha256": "e4a946af03909a6af8e529d8ac1c33edc7f65b771708cd12bc36204916d60736",
          "sha1": "dff772064fa8c8fc89dadf1249396e9858178e66",
          "md5": "abab507cc184e500695cf3b8082d8098"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "publishing-plugin-one-1.0.0-local-dev-javadoc.jar",
          "url": "publishing-plugin-one-1.0.0-local-dev-javadoc.jar",
          "size": 261,
          "sha512": "a2d08703a245f419763778eb4d415e6a6566c7ff570716bfedce0907a35f657d72651a5ac043f494b65604b14199db60978f82ceb36ef18e632ba2f362c52a5d",
          "sha256": "96dd72aef7464ae341a36ca6b1254d5ecb020105f936fbfc9b3d754e2ecbc729",
          "sha1": "8305657a92d4c734752d5f2711d152aa4f3eba0b",
          "md5": "cd1b0d5e94a03b023dbe54ad422d99d7"
        }
      ]
    }
  ]
}
