/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    includeBuild("build-logic/settings")
    includeBuild("build-logic/plugins")
}

plugins {
    id("kotlin-project-root-settings")
}

rootProject.name = "jvm"
include("modules:applications:app", "modules:libraries:list", "modules:libraries:utilities")

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}

buildCache {
    local {
        isEnabled = true
        isPush = true
    }
}
