[versions]
kotlin = "2.0.0"
junit = "5.10.1"
junitPlatform = "1.10.1"
coroutines = "1.8.1"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#kotlinDsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDsl" }
