{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "consumerPlugin",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "consumerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "consumerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "f5d92b2917801e77e0f81a20dc25923ce89e6a36b248c0b2b60a1bda7da3bcdd336ef02495a400fac93aada89ba1377ca5079a2fc6a88ca305e7d23761ac47a9",
          "sha256": "851bac8221771b2a9cc4261659596da1f00a46a40ccd7416937a7dc596995b2c",
          "sha1": "ae555c1bb6ad2eeca4abd3146de242525b1b5780",
          "md5": "79f9f1167457526519c4e4d47c1ccd68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nophasenokill",
          "module": "producerPlugin",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "consumerPlugin-1.0.0-SNAPSHOT.jar",
          "url": "consumerPlugin-1.0.0-SNAPSHOT.jar",
          "size": 3188,
          "sha512": "f5d92b2917801e77e0f81a20dc25923ce89e6a36b248c0b2b60a1bda7da3bcdd336ef02495a400fac93aada89ba1377ca5079a2fc6a88ca305e7d23761ac47a9",
          "sha256": "851bac8221771b2a9cc4261659596da1f00a46a40ccd7416937a7dc596995b2c",
          "sha1": "ae555c1bb6ad2eeca4abd3146de242525b1b5780",
          "md5": "79f9f1167457526519c4e4d47c1ccd68"
        }
      ]
    }
  ]
}
