{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "standalone-kotlin-base-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "url": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "size": 320767,
          "sha512": "4855920db61dcd5278c14ba9732114b6c2b6ff70f297a2c709a2b50de5447e3e398ccb22780a7c442e683a51f711fb54eaf9f6acda4be5c52dc61f539aa1fa86",
          "sha256": "5910b114a2b13f5fdd1e58a9c4cdba3c779e0ff6f5fff3181809054b13234475",
          "sha1": "514140e31f98312c585461ea14c6074716d07949",
          "md5": "08ac0330ee3bbfcc1b0aa05061a555a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "url": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "size": 320767,
          "sha512": "4855920db61dcd5278c14ba9732114b6c2b6ff70f297a2c709a2b50de5447e3e398ccb22780a7c442e683a51f711fb54eaf9f6acda4be5c52dc61f539aa1fa86",
          "sha256": "5910b114a2b13f5fdd1e58a9c4cdba3c779e0ff6f5fff3181809054b13234475",
          "sha1": "514140e31f98312c585461ea14c6074716d07949",
          "md5": "08ac0330ee3bbfcc1b0aa05061a555a2"
        }
      ]
    }
  ]
}
