{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "standalone-kotlin-base-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "url": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "size": 320767,
          "sha512": "d77f62679e7129f35381c87f514916817ca66d6264f23e296222a59b37baad11b14510872d57ce6efc60de4188d9359d9ac8b7201cee35035ed943f3f3d3d6af",
          "sha256": "01722958160e3d8eb41890fc12615599d270b7a12f13aa2d2a12907aecd75d55",
          "sha1": "8b146e43e7eb248145ec788efb92b3624b7a2307",
          "md5": "b6f6599cd71ca99da5088190c03c369a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "url": "standalone-kotlin-base-plugin-1.0.0-local-dev.jar",
          "size": 320767,
          "sha512": "d77f62679e7129f35381c87f514916817ca66d6264f23e296222a59b37baad11b14510872d57ce6efc60de4188d9359d9ac8b7201cee35035ed943f3f3d3d6af",
          "sha256": "01722958160e3d8eb41890fc12615599d270b7a12f13aa2d2a12907aecd75d55",
          "sha1": "8b146e43e7eb248145ec788efb92b3624b7a2307",
          "md5": "b6f6599cd71ca99da5088190c03c369a"
        }
      ]
    }
  ]
}
