{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "root-settings-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "root-settings-plugin-1.0.0-local-dev.jar",
          "url": "root-settings-plugin-1.0.0-local-dev.jar",
          "size": 22558,
          "sha512": "10c65dc4b49a56ea3a10744f86b9622881a9f8a52e9226a4145db682546134951fa9b2cc87d820ca3432e64c576c44f5905be5c6983f815306ea8c81fae45475",
          "sha256": "e69fe2ac101a97492fff61a3ff114fa9b539a83321db80574678dbd05642137d",
          "sha1": "8ea95503da1505086a0f0c0f9bcbfe56aa60695b",
          "md5": "47e1f84090420a95084fa62e5a9352e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains",
          "module": "foojay-resolver",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "root-settings-plugin-1.0.0-local-dev.jar",
          "url": "root-settings-plugin-1.0.0-local-dev.jar",
          "size": 22558,
          "sha512": "10c65dc4b49a56ea3a10744f86b9622881a9f8a52e9226a4145db682546134951fa9b2cc87d820ca3432e64c576c44f5905be5c6983f815306ea8c81fae45475",
          "sha256": "e69fe2ac101a97492fff61a3ff114fa9b539a83321db80574678dbd05642137d",
          "sha1": "8ea95503da1505086a0f0c0f9bcbfe56aa60695b",
          "md5": "47e1f84090420a95084fa62e5a9352e5"
        }
      ]
    }
  ]
}
