{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "consumer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "d0491d32a64b16c704bdf4078cfcd04b9cfb4b47902a4010f98209d9a6a57bf2614b95a84e42f67fe193f362920264c0cd28a9b9fe7e763611ebf455691c5c0d",
          "sha256": "ee8df82275d6920e8933450d4a27016981a1069c32615fd8a2f8d74cb871e095",
          "sha1": "792caa92c0fe9235f3ba21f7aba78eb4820334e5",
          "md5": "9b8cb8eef6bc0082239929a189dc0044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "producer-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "standalone-kotlin-base-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        }
      ],
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "d0491d32a64b16c704bdf4078cfcd04b9cfb4b47902a4010f98209d9a6a57bf2614b95a84e42f67fe193f362920264c0cd28a9b9fe7e763611ebf455691c5c0d",
          "sha256": "ee8df82275d6920e8933450d4a27016981a1069c32615fd8a2f8d74cb871e095",
          "sha1": "792caa92c0fe9235f3ba21f7aba78eb4820334e5",
          "md5": "9b8cb8eef6bc0082239929a189dc0044"
        }
      ]
    }
  ]
}
