{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "consumer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "9bd4b6d23e9662d0477484c154dcfe36650fae75916d91b9fc748356125b79c53f07b6088816fa0eeb25419c6229ef0f911c8f846dd75c74b84b263f54126d1a",
          "sha256": "2aa9d47ab0ea1dd58451553d91a2e5b2649837e67ee9e37ba7733cd0520e5cc3",
          "sha1": "edf68f27842b53de9eb1daf53cedc6fb4277bf9c",
          "md5": "a93860d378d21ed1451f12af10cfc640"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "producer-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "standalone-kotlin-base-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        }
      ],
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "9bd4b6d23e9662d0477484c154dcfe36650fae75916d91b9fc748356125b79c53f07b6088816fa0eeb25419c6229ef0f911c8f846dd75c74b84b263f54126d1a",
          "sha256": "2aa9d47ab0ea1dd58451553d91a2e5b2649837e67ee9e37ba7733cd0520e5cc3",
          "sha1": "edf68f27842b53de9eb1daf53cedc6fb4277bf9c",
          "md5": "a93860d378d21ed1451f12af10cfc640"
        }
      ]
    }
  ]
}
