{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "consumer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "cb63d7899a212d69c27f4b9c8fdf72cf54de40b4ab954ebc520ebdcd78559de933260a6f3954df347eedc2da30b9769bfe69fa719344703a9e432721f7619144",
          "sha256": "8c9c76f55314b622d0d22184c92e5ccd9e466bb1ed081b3b812ef2ecd0ff565a",
          "sha1": "e3e7bbe1abc9c917ba65bbcf726d90fc4d1128cc",
          "md5": "64b4c84f8ff23850ac95e29cc5c92adf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "producer-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        },
        {
          "group": "com.nophasenokill",
          "module": "standalone-kotlin-base-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        }
      ],
      "files": [
        {
          "name": "consumer-plugin-1.0.0-local-dev.jar",
          "url": "consumer-plugin-1.0.0-local-dev.jar",
          "size": 3012,
          "sha512": "cb63d7899a212d69c27f4b9c8fdf72cf54de40b4ab954ebc520ebdcd78559de933260a6f3954df347eedc2da30b9769bfe69fa719344703a9e432721f7619144",
          "sha256": "8c9c76f55314b622d0d22184c92e5ccd9e466bb1ed081b3b812ef2ecd0ff565a",
          "sha1": "e3e7bbe1abc9c917ba65bbcf726d90fc4d1128cc",
          "md5": "64b4c84f8ff23850ac95e29cc5c92adf"
        }
      ]
    }
  ]
}
