{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 7863,
          "sha512": "12d578307b383c8fc7bb2cf4ecdce32997bacc8126b11a59d523ea14ffafa8fa76f649d150e4978aba7798eded66ccc329c79aa06c73d04131277bbabca4e55e",
          "sha256": "1141795225f3a647fbdb14c0b7985c1e15a76b281ae5d035f3c088e6437972a8",
          "sha1": "4383c1128c1ca63c8291a33d43924eb39ce44747",
          "md5": "4f80ac7ff0974607b4ea26bc05cf50ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nophasenokill",
          "module": "standalone-kotlin-base-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        }
      ],
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 7863,
          "sha512": "12d578307b383c8fc7bb2cf4ecdce32997bacc8126b11a59d523ea14ffafa8fa76f649d150e4978aba7798eded66ccc329c79aa06c73d04131277bbabca4e55e",
          "sha256": "1141795225f3a647fbdb14c0b7985c1e15a76b281ae5d035f3c088e6437972a8",
          "sha1": "4383c1128c1ca63c8291a33d43924eb39ce44747",
          "md5": "4f80ac7ff0974607b4ea26bc05cf50ee"
        }
      ]
    }
  ]
}
