{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 7863,
          "sha512": "340eb0dc5b95a985387f06edc62561247c8d2e3e85fea69dac1bdbd403a86a8a2768b11be9c3bb9464df72dc3565ce13f17bc4f3035061ab8fe9c7d716e3adbb",
          "sha256": "21c9a989ef6ecc8536c6b6335c04d2ad7924485578e2c3ee83c2d48b80f5081b",
          "sha1": "7aad8549c8c35d9857fc29e96ba6cc8bcaa36bf7",
          "md5": "c039ad5068efe3572ee5cc83ed513694"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.nophasenokill",
          "module": "standalone-kotlin-base-plugin",
          "version": {
            "requires": "1.0.0-local-dev"
          }
        }
      ],
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 7863,
          "sha512": "340eb0dc5b95a985387f06edc62561247c8d2e3e85fea69dac1bdbd403a86a8a2768b11be9c3bb9464df72dc3565ce13f17bc4f3035061ab8fe9c7d716e3adbb",
          "sha256": "21c9a989ef6ecc8536c6b6335c04d2ad7924485578e2c3ee83c2d48b80f5081b",
          "sha1": "7aad8549c8c35d9857fc29e96ba6cc8bcaa36bf7",
          "md5": "c039ad5068efe3572ee5cc83ed513694"
        }
      ]
    }
  ]
}
