{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nophasenokill",
    "module": "producer-plugin",
    "version": "1.0.0-local-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 4856,
          "sha512": "b3a0e507f040cc898b01dd9174e923a994bd961455b88091bb03a480134d79901103ad1d1a8206b25767237272a059343a8972dd10d0053fc4de840ab54d9ce1",
          "sha256": "ad16b060e48e62e595d6127f12378cbb2e96561d6228d0742da0e373b7c221b2",
          "sha1": "06d0de5530e4e66ce0fb81db058a2d722409b708",
          "md5": "986102e38836400c7e8cb358d9f2ec71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "producer-plugin-1.0.0-local-dev.jar",
          "url": "producer-plugin-1.0.0-local-dev.jar",
          "size": 4856,
          "sha512": "b3a0e507f040cc898b01dd9174e923a994bd961455b88091bb03a480134d79901103ad1d1a8206b25767237272a059343a8972dd10d0053fc4de840ab54d9ce1",
          "sha256": "ad16b060e48e62e595d6127f12378cbb2e96561d6228d0742da0e373b7c221b2",
          "sha1": "06d0de5530e4e66ce0fb81db058a2d722409b708",
          "md5": "986102e38836400c7e8cb358d9f2ec71"
        }
      ]
    }
  ]
}
