version: 5
cache:
  accessControl:
    users:
      DEFAULT_CACHE_USER:
        level: readwrite
        password: 4om/2PiwdR9XsvqhlaR72bjmV7dlFtgI5ABbYX/PdkE=:Ebf4U8J84KWAs9BQdYy/zCWlMcWsmapthV6l34wvUfk=
        note: ""
    anonymousLevel: none
  freeSpaceBufferSize: 1024
  maxEntryAgeInHours: 168
  targetSize:
    type: fixed
    size: 10000
  maxArtifactSize: 100
registration: null
uiAccess:
  type: secure
  username: DEFAULT_USERNAME
  password: +VRUzrvG0cMObN7L+n773wI7INZ4CyAjSVWBpL9+Hls=:2vItqZITjaZXV6HZ2by7r/W6rzkUGp6UriEPsiL+K/Q=
