[versions]
kotlin = "1.9.22"
kotlinDsl = "4.3.0"
junit = "5.10.1"
junitPlatform = "1.10.1"

[plugins]
#kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#kotlinDsl = { id = "org.gradle.kotlin:gradle-kotlin-dsl-plugins", version.ref = "kotlinDsl" }
