[versions]
## BOM's/frequently updated
kotlin = "1.9.23"
coroutines = "1.8.0"
slf4j = "2.0.12"
gradle = "8.7"
junit = "5.10.1"
commonsIo = "2.16.0"

#kotlinDsl = "4.3.0"



#springBootDependencies = "3.2.0"
#talaiot = "2.0.3"
#
## External plugins
#dependencyAnalysisGradlePlugin = "1.29.0"
#foojayResolver = "0.7.0"
#gradleEnterpriseGradlePlugin = "3.16.2"
#commonCustomUserDataGradlePlugin = "1.12.1"
#
## Standard deps
#checkerQual = "3.21.4"
#commonsText = "1.11.0"
#commonsIo = "2.5"
#commonsCodec = "1.9"
#errorProneAnnotations = "2.13.1"
#gson = "2.10.1"
#jakartaActivationApi = "1.2.2"
#javaxActivation = "1.1.1"
#
[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#kotlinDsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDsl" }
