[versions]
foojay-resolver = "0.7.0"
gradle-enterprise-gradle-plugin = "3.16.1"

[libraries]
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay-resolver" }
gradle-enterprise-gradle-plugin = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle-enterprise-gradle-plugin" }

